// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import (
	"database/sql"

	"github.com/lib/pq"
)

// Affiliat represents a row from 'equinox.affiliat'.
type Affiliat struct {
	Affcustaccountno sql.NullString  `json:"affcustaccountno"` // affcustaccountno
	Affsavingytd     sql.NullFloat64 `json:"affsavingytd"`     // affsavingytd
	Affsavingmtd     sql.NullFloat64 `json:"affsavingmtd"`     // affsavingmtd
	Affchangedate    pq.NullTime     `json:"affchangedate"`    // affchangedate
	Affsparec1       sql.NullString  `json:"affsparec1"`       // affsparec1
	Affsparec2       sql.NullString  `json:"affsparec2"`       // affsparec2
	Affsparec3       sql.NullString  `json:"affsparec3"`       // affsparec3
	Affspared1       pq.NullTime     `json:"affspared1"`       // affspared1
	Affspared2       pq.NullTime     `json:"affspared2"`       // affspared2
	Affspared3       pq.NullTime     `json:"affspared3"`       // affspared3
	Affsparen1       sql.NullFloat64 `json:"affsparen1"`       // affsparen1
	Affsparen2       sql.NullFloat64 `json:"affsparen2"`       // affsparen2
	Affsparen3       sql.NullFloat64 `json:"affsparen3"`       // affsparen3
	EquinoxLrn       int64           `json:"equinox_lrn"`      // equinox_lrn
	EquinoxSec       sql.NullInt64   `json:"equinox_sec"`      // equinox_sec
}

// AffiliatByEquinoxLrn retrieves a row from 'equinox.affiliat' as a Affiliat.
//
// Generated from index 'affiliat_pkey'.
func AffiliatByEquinoxLrn(db XODB, equinoxLrn int64) (*Affiliat, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`affcustaccountno, affsavingytd, affsavingmtd, affchangedate, affsparec1, affsparec2, affsparec3, affspared1, affspared2, affspared3, affsparen1, affsparen2, affsparen3, equinox_lrn, equinox_sec ` +
		`FROM equinox.affiliat ` +
		`WHERE equinox_lrn = $1`

	// run query
	XOLog(sqlstr, equinoxLrn)
	a := Affiliat{}

	err = db.QueryRow(sqlstr, equinoxLrn).Scan(&a.Affcustaccountno, &a.Affsavingytd, &a.Affsavingmtd, &a.Affchangedate, &a.Affsparec1, &a.Affsparec2, &a.Affsparec3, &a.Affspared1, &a.Affspared2, &a.Affspared3, &a.Affsparen1, &a.Affsparen2, &a.Affsparen3, &a.EquinoxLrn, &a.EquinoxSec)
	if err != nil {
		return nil, err
	}

	return &a, nil
}
