// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// AprjfileBlb represents a row from 'equinox.aprjfile_blb'.
type AprjfileBlb struct {
	BlbLrn  int64          `json:"blb_lrn"`  // blb_lrn
	BlbData []byte         `json:"blb_data"` // blb_data
	BlbText sql.NullString `json:"blb_text"` // blb_text
}

func AllAprjfileBlb(db XODB, callback func(x AprjfileBlb) bool) error {

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.aprjfile_blb `

	q, err := db.Query(sqlstr)

	if err != nil {
		return err
	}
	defer q.Close()

	// load results
	for q.Next() {
		ab := AprjfileBlb{}

		// scan
		err = q.Scan(&ab.BlbLrn, &ab.BlbData, &ab.BlbText)
		if err != nil {
			return err
		}
		if !callback(ab) {
			return nil
		}
	}

	return nil
}

// AprjfileBlbByBlbLrn retrieves a row from 'equinox.aprjfile_blb' as a AprjfileBlb.
//
// Generated from index 'aprjfile_blb_pkey'.
func AprjfileBlbByBlbLrn(db XODB, blbLrn int64) (*AprjfileBlb, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.aprjfile_blb ` +
		`WHERE blb_lrn = $1`

	// run query
	XOLog(sqlstr, blbLrn)
	ab := AprjfileBlb{}

	err = db.QueryRow(sqlstr, blbLrn).Scan(&ab.BlbLrn, &ab.BlbData, &ab.BlbText)
	if err != nil {
		return nil, err
	}

	return &ab, nil
}
