// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import (
	"database/sql"

	"github.com/lib/pq"
)

// Excustac represents a row from 'equinox.excustac'.
type Excustac struct {
	Excustacno      sql.NullString `json:"excustacno"`      // excustacno
	Excustacdate    pq.NullTime    `json:"excustacdate"`    // excustacdate
	Excustacquality sql.NullInt64  `json:"excustacquality"` // excustacquality
	EquinoxPrn      sql.NullInt64  `json:"equinox_prn"`     // equinox_prn
	EquinoxLrn      int64          `json:"equinox_lrn"`     // equinox_lrn
	EquinoxSec      sql.NullInt64  `json:"equinox_sec"`     // equinox_sec
}

func AllExcustac(db XODB, callback func(x Excustac) bool) error {

	// sql query
	const sqlstr = `SELECT ` +
		`excustacno, excustacdate, excustacquality, equinox_prn, equinox_lrn, equinox_sec ` +
		`FROM equinox.excustac `

	q, err := db.Query(sqlstr)

	if err != nil {
		return err
	}
	defer q.Close()

	// load results
	for q.Next() {
		e := Excustac{}

		// scan
		err = q.Scan(&e.Excustacno, &e.Excustacdate, &e.Excustacquality, &e.EquinoxPrn, &e.EquinoxLrn, &e.EquinoxSec)
		if err != nil {
			return err
		}
		if !callback(e) {
			return nil
		}
	}

	return nil
}

// ExcustacByEquinoxLrn retrieves a row from 'equinox.excustac' as a Excustac.
//
// Generated from index 'excustac_pkey'.
func ExcustacByEquinoxLrn(db XODB, equinoxLrn int64) (*Excustac, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`excustacno, excustacdate, excustacquality, equinox_prn, equinox_lrn, equinox_sec ` +
		`FROM equinox.excustac ` +
		`WHERE equinox_lrn = $1`

	// run query
	XOLog(sqlstr, equinoxLrn)
	e := Excustac{}

	err = db.QueryRow(sqlstr, equinoxLrn).Scan(&e.Excustacno, &e.Excustacdate, &e.Excustacquality, &e.EquinoxPrn, &e.EquinoxLrn, &e.EquinoxSec)
	if err != nil {
		return nil, err
	}

	return &e, nil
}
