// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import (
	"database/sql"

	"github.com/lib/pq"
)

// Exfast represents a row from 'equinox.exfast'.
type Exfast struct {
	Exfspromo       sql.NullString `json:"exfspromo"`       // exfspromo
	Exfsstartdate   pq.NullTime    `json:"exfsstartdate"`   // exfsstartdate
	Exfsenddate     pq.NullTime    `json:"exfsenddate"`     // exfsenddate
	Exfslivedate    pq.NullTime    `json:"exfslivedate"`    // exfslivedate
	Exfscompleted   pq.NullTime    `json:"exfscompleted"`   // exfscompleted
	Exfsgscustsgath sql.NullInt64  `json:"exfsgscustsgath"` // exfsgscustsgath
	Exfsgscustslive sql.NullInt64  `json:"exfsgscustslive"` // exfsgscustslive
	Exfscustsgath   sql.NullInt64  `json:"exfscustsgath"`   // exfscustsgath
	Exfscustslive   sql.NullInt64  `json:"exfscustslive"`   // exfscustslive
	Exfspaid        sql.NullInt64  `json:"exfspaid"`        // exfspaid
	EquinoxPrn      sql.NullInt64  `json:"equinox_prn"`     // equinox_prn
	EquinoxLrn      int64          `json:"equinox_lrn"`     // equinox_lrn
	EquinoxSec      sql.NullInt64  `json:"equinox_sec"`     // equinox_sec
}

func AllExfast(db XODB, callback func(x Exfast) bool) error {

	// sql query
	const sqlstr = `SELECT ` +
		`exfspromo, exfsstartdate, exfsenddate, exfslivedate, exfscompleted, exfsgscustsgath, exfsgscustslive, exfscustsgath, exfscustslive, exfspaid, equinox_prn, equinox_lrn, equinox_sec ` +
		`FROM equinox.exfast `

	q, err := db.Query(sqlstr)

	if err != nil {
		return err
	}
	defer q.Close()

	// load results
	for q.Next() {
		e := Exfast{}

		// scan
		err = q.Scan(&e.Exfspromo, &e.Exfsstartdate, &e.Exfsenddate, &e.Exfslivedate, &e.Exfscompleted, &e.Exfsgscustsgath, &e.Exfsgscustslive, &e.Exfscustsgath, &e.Exfscustslive, &e.Exfspaid, &e.EquinoxPrn, &e.EquinoxLrn, &e.EquinoxSec)
		if err != nil {
			return err
		}
		if !callback(e) {
			return nil
		}
	}

	return nil
}

// ExfastByEquinoxLrn retrieves a row from 'equinox.exfast' as a Exfast.
//
// Generated from index 'exfast_pkey'.
func ExfastByEquinoxLrn(db XODB, equinoxLrn int64) (*Exfast, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`exfspromo, exfsstartdate, exfsenddate, exfslivedate, exfscompleted, exfsgscustsgath, exfsgscustslive, exfscustsgath, exfscustslive, exfspaid, equinox_prn, equinox_lrn, equinox_sec ` +
		`FROM equinox.exfast ` +
		`WHERE equinox_lrn = $1`

	// run query
	XOLog(sqlstr, equinoxLrn)
	e := Exfast{}

	err = db.QueryRow(sqlstr, equinoxLrn).Scan(&e.Exfspromo, &e.Exfsstartdate, &e.Exfsenddate, &e.Exfslivedate, &e.Exfscompleted, &e.Exfsgscustsgath, &e.Exfsgscustslive, &e.Exfscustsgath, &e.Exfscustslive, &e.Exfspaid, &e.EquinoxPrn, &e.EquinoxLrn, &e.EquinoxSec)
	if err != nil {
		return nil, err
	}

	return &e, nil
}
