// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// Ghostcli represents a row from 'equinox.ghostcli'.
type Ghostcli struct {
	Ghostclinumber  sql.NullString `json:"ghostclinumber"`  // ghostclinumber
	Ghostclirealnum sql.NullString `json:"ghostclirealnum"` // ghostclirealnum
	EquinoxLrn      int64          `json:"equinox_lrn"`     // equinox_lrn
	EquinoxSec      sql.NullInt64  `json:"equinox_sec"`     // equinox_sec
}

func AllGhostcli(db XODB, callback func(x Ghostcli) bool) error {

	// sql query
	const sqlstr = `SELECT ` +
		`ghostclinumber, ghostclirealnum, equinox_lrn, equinox_sec ` +
		`FROM equinox.ghostcli `

	q, err := db.Query(sqlstr)

	if err != nil {
		return err
	}
	defer q.Close()

	// load results
	for q.Next() {
		g := Ghostcli{}

		// scan
		err = q.Scan(&g.Ghostclinumber, &g.Ghostclirealnum, &g.EquinoxLrn, &g.EquinoxSec)
		if err != nil {
			return err
		}
		if !callback(g) {
			return nil
		}
	}

	return nil
}

// GhostcliByEquinoxLrn retrieves a row from 'equinox.ghostcli' as a Ghostcli.
//
// Generated from index 'ghostcli_pkey'.
func GhostcliByEquinoxLrn(db XODB, equinoxLrn int64) (*Ghostcli, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`ghostclinumber, ghostclirealnum, equinox_lrn, equinox_sec ` +
		`FROM equinox.ghostcli ` +
		`WHERE equinox_lrn = $1`

	// run query
	XOLog(sqlstr, equinoxLrn)
	g := Ghostcli{}

	err = db.QueryRow(sqlstr, equinoxLrn).Scan(&g.Ghostclinumber, &g.Ghostclirealnum, &g.EquinoxLrn, &g.EquinoxSec)
	if err != nil {
		return nil, err
	}

	return &g, nil
}
