// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// HomedelBlb represents a row from 'equinox.homedel_blb'.
type HomedelBlb struct {
	BlbLrn  int64          `json:"blb_lrn"`  // blb_lrn
	BlbData []byte         `json:"blb_data"` // blb_data
	BlbText sql.NullString `json:"blb_text"` // blb_text
}

// HomedelBlbByBlbLrn retrieves a row from 'equinox.homedel_blb' as a HomedelBlb.
//
// Generated from index 'homedel_blb_pkey'.
func HomedelBlbByBlbLrn(db XODB, blbLrn int64) (*HomedelBlb, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.homedel_blb ` +
		`WHERE blb_lrn = $1`

	// run query
	XOLog(sqlstr, blbLrn)
	hb := HomedelBlb{}

	err = db.QueryRow(sqlstr, blbLrn).Scan(&hb.BlbLrn, &hb.BlbData, &hb.BlbText)
	if err != nil {
		return nil, err
	}

	return &hb, nil
}
