// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// HsSpecBlb represents a row from 'equinox.hs_spec_blb'.
type HsSpecBlb struct {
	BlbLrn  int64          `json:"blb_lrn"`  // blb_lrn
	BlbData []byte         `json:"blb_data"` // blb_data
	BlbText sql.NullString `json:"blb_text"` // blb_text
}

func AllHsSpecBlb(db XODB, callback func(x HsSpecBlb) bool) error {

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.hs_spec_blb `

	q, err := db.Query(sqlstr)

	if err != nil {
		return err
	}
	defer q.Close()

	// load results
	for q.Next() {
		hsb := HsSpecBlb{}

		// scan
		err = q.Scan(&hsb.BlbLrn, &hsb.BlbData, &hsb.BlbText)
		if err != nil {
			return err
		}
		if !callback(hsb) {
			return nil
		}
	}

	return nil
}

// HsSpecBlbByBlbLrn retrieves a row from 'equinox.hs_spec_blb' as a HsSpecBlb.
//
// Generated from index 'hs_spec_blb_pkey'.
func HsSpecBlbByBlbLrn(db XODB, blbLrn int64) (*HsSpecBlb, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.hs_spec_blb ` +
		`WHERE blb_lrn = $1`

	// run query
	XOLog(sqlstr, blbLrn)
	hsb := HsSpecBlb{}

	err = db.QueryRow(sqlstr, blbLrn).Scan(&hsb.BlbLrn, &hsb.BlbData, &hsb.BlbText)
	if err != nil {
		return nil, err
	}

	return &hsb, nil
}
