// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// ImeiBlb represents a row from 'equinox.imei_blb'.
type ImeiBlb struct {
	BlbLrn  int64          `json:"blb_lrn"`  // blb_lrn
	BlbData []byte         `json:"blb_data"` // blb_data
	BlbText sql.NullString `json:"blb_text"` // blb_text
}

// ImeiBlbByBlbLrn retrieves a row from 'equinox.imei_blb' as a ImeiBlb.
//
// Generated from index 'imei_blb_pkey'.
func ImeiBlbByBlbLrn(db XODB, blbLrn int64) (*ImeiBlb, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.imei_blb ` +
		`WHERE blb_lrn = $1`

	// run query
	XOLog(sqlstr, blbLrn)
	ib := ImeiBlb{}

	err = db.QueryRow(sqlstr, blbLrn).Scan(&ib.BlbLrn, &ib.BlbData, &ib.BlbText)
	if err != nil {
		return nil, err
	}

	return &ib, nil
}
