// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// NrgsuppBlb represents a row from 'equinox.nrgsupp_blb'.
type NrgsuppBlb struct {
	BlbLrn  int64          `json:"blb_lrn"`  // blb_lrn
	BlbData []byte         `json:"blb_data"` // blb_data
	BlbText sql.NullString `json:"blb_text"` // blb_text
}

func AllNrgsuppBlb(db XODB, callback func(x NrgsuppBlb) bool) error {

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.nrgsupp_blb `

	q, err := db.Query(sqlstr)

	if err != nil {
		return err
	}
	defer q.Close()

	// load results
	for q.Next() {
		nb := NrgsuppBlb{}

		// scan
		err = q.Scan(&nb.BlbLrn, &nb.BlbData, &nb.BlbText)
		if err != nil {
			return err
		}
		if !callback(nb) {
			return nil
		}
	}

	return nil
}

// NrgsuppBlbByBlbLrn retrieves a row from 'equinox.nrgsupp_blb' as a NrgsuppBlb.
//
// Generated from index 'nrgsupp_blb_pkey'.
func NrgsuppBlbByBlbLrn(db XODB, blbLrn int64) (*NrgsuppBlb, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.nrgsupp_blb ` +
		`WHERE blb_lrn = $1`

	// run query
	XOLog(sqlstr, blbLrn)
	nb := NrgsuppBlb{}

	err = db.QueryRow(sqlstr, blbLrn).Scan(&nb.BlbLrn, &nb.BlbData, &nb.BlbText)
	if err != nil {
		return nil, err
	}

	return &nb, nil
}
