// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// Optmonth represents a row from 'equinox.optmonth'.
type Optmonth struct {
	Ommonth         sql.NullString `json:"ommonth"`         // ommonth
	Omcustsnqservs1 sql.NullInt64  `json:"omcustsnqservs1"` // omcustsnqservs1
	Omcustsnqservs2 sql.NullInt64  `json:"omcustsnqservs2"` // omcustsnqservs2
	Omcustsnqservs3 sql.NullInt64  `json:"omcustsnqservs3"` // omcustsnqservs3
	Omcustsnqservs4 sql.NullInt64  `json:"omcustsnqservs4"` // omcustsnqservs4
	Omcustsnqservs5 sql.NullInt64  `json:"omcustsnqservs5"` // omcustsnqservs5
	Omcustsqservs1  sql.NullInt64  `json:"omcustsqservs1"`  // omcustsqservs1
	Omcustsqservs2  sql.NullInt64  `json:"omcustsqservs2"`  // omcustsqservs2
	Omcustsqservs3  sql.NullInt64  `json:"omcustsqservs3"`  // omcustsqservs3
	Omcustsqservs4  sql.NullInt64  `json:"omcustsqservs4"`  // omcustsqservs4
	Omcustsqservs5  sql.NullInt64  `json:"omcustsqservs5"`  // omcustsqservs5
	EquinoxPrn      sql.NullInt64  `json:"equinox_prn"`     // equinox_prn
	EquinoxLrn      int64          `json:"equinox_lrn"`     // equinox_lrn
	EquinoxSec      sql.NullInt64  `json:"equinox_sec"`     // equinox_sec
}

func AllOptmonth(db XODB, callback func(x Optmonth) bool) error {

	// sql query
	const sqlstr = `SELECT ` +
		`ommonth, omcustsnqservs1, omcustsnqservs2, omcustsnqservs3, omcustsnqservs4, omcustsnqservs5, omcustsqservs1, omcustsqservs2, omcustsqservs3, omcustsqservs4, omcustsqservs5, equinox_prn, equinox_lrn, equinox_sec ` +
		`FROM equinox.optmonth `

	q, err := db.Query(sqlstr)

	if err != nil {
		return err
	}
	defer q.Close()

	// load results
	for q.Next() {
		o := Optmonth{}

		// scan
		err = q.Scan(&o.Ommonth, &o.Omcustsnqservs1, &o.Omcustsnqservs2, &o.Omcustsnqservs3, &o.Omcustsnqservs4, &o.Omcustsnqservs5, &o.Omcustsqservs1, &o.Omcustsqservs2, &o.Omcustsqservs3, &o.Omcustsqservs4, &o.Omcustsqservs5, &o.EquinoxPrn, &o.EquinoxLrn, &o.EquinoxSec)
		if err != nil {
			return err
		}
		if !callback(o) {
			return nil
		}
	}

	return nil
}

// OptmonthByEquinoxLrn retrieves a row from 'equinox.optmonth' as a Optmonth.
//
// Generated from index 'optmonth_pkey'.
func OptmonthByEquinoxLrn(db XODB, equinoxLrn int64) (*Optmonth, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`ommonth, omcustsnqservs1, omcustsnqservs2, omcustsnqservs3, omcustsnqservs4, omcustsnqservs5, omcustsqservs1, omcustsqservs2, omcustsqservs3, omcustsqservs4, omcustsqservs5, equinox_prn, equinox_lrn, equinox_sec ` +
		`FROM equinox.optmonth ` +
		`WHERE equinox_lrn = $1`

	// run query
	XOLog(sqlstr, equinoxLrn)
	o := Optmonth{}

	err = db.QueryRow(sqlstr, equinoxLrn).Scan(&o.Ommonth, &o.Omcustsnqservs1, &o.Omcustsnqservs2, &o.Omcustsnqservs3, &o.Omcustsnqservs4, &o.Omcustsnqservs5, &o.Omcustsqservs1, &o.Omcustsqservs2, &o.Omcustsqservs3, &o.Omcustsqservs4, &o.Omcustsqservs5, &o.EquinoxPrn, &o.EquinoxLrn, &o.EquinoxSec)
	if err != nil {
		return nil, err
	}

	return &o, nil
}
