// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// Propval represents a row from 'equinox.propval'.
type Propval struct {
	Pvuniquesys   sql.NullFloat64 `json:"pvuniquesys"`   // pvuniquesys
	Pvpropertyid  sql.NullFloat64 `json:"pvpropertyid"`  // pvpropertyid
	Pvuniqueid    sql.NullString  `json:"pvuniqueid"`    // pvuniqueid
	Pvvalue       sql.NullString  `json:"pvvalue"`       // pvvalue
	Pvdescription sql.NullInt64   `json:"pvdescription"` // pvdescription
	Pvbeforesave  sql.NullInt64   `json:"pvbeforesave"`  // pvbeforesave
	Pvaftersave   sql.NullInt64   `json:"pvaftersave"`   // pvaftersave
	Pvbeforefield sql.NullInt64   `json:"pvbeforefield"` // pvbeforefield
	Pvafterfield  sql.NullInt64   `json:"pvafterfield"`  // pvafterfield
	Pvadditional  sql.NullInt64   `json:"pvadditional"`  // pvadditional
	EquinoxLrn    int64           `json:"equinox_lrn"`   // equinox_lrn
	EquinoxSec    sql.NullInt64   `json:"equinox_sec"`   // equinox_sec
}

func AllPropval(db XODB, callback func(x Propval) bool) error {

	// sql query
	const sqlstr = `SELECT ` +
		`pvuniquesys, pvpropertyid, pvuniqueid, pvvalue, pvdescription, pvbeforesave, pvaftersave, pvbeforefield, pvafterfield, pvadditional, equinox_lrn, equinox_sec ` +
		`FROM equinox.propval `

	q, err := db.Query(sqlstr)

	if err != nil {
		return err
	}
	defer q.Close()

	// load results
	for q.Next() {
		p := Propval{}

		// scan
		err = q.Scan(&p.Pvuniquesys, &p.Pvpropertyid, &p.Pvuniqueid, &p.Pvvalue, &p.Pvdescription, &p.Pvbeforesave, &p.Pvaftersave, &p.Pvbeforefield, &p.Pvafterfield, &p.Pvadditional, &p.EquinoxLrn, &p.EquinoxSec)
		if err != nil {
			return err
		}
		if !callback(p) {
			return nil
		}
	}

	return nil
}

// PropvalByEquinoxLrn retrieves a row from 'equinox.propval' as a Propval.
//
// Generated from index 'propval_pkey'.
func PropvalByEquinoxLrn(db XODB, equinoxLrn int64) (*Propval, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`pvuniquesys, pvpropertyid, pvuniqueid, pvvalue, pvdescription, pvbeforesave, pvaftersave, pvbeforefield, pvafterfield, pvadditional, equinox_lrn, equinox_sec ` +
		`FROM equinox.propval ` +
		`WHERE equinox_lrn = $1`

	// run query
	XOLog(sqlstr, equinoxLrn)
	p := Propval{}

	err = db.QueryRow(sqlstr, equinoxLrn).Scan(&p.Pvuniquesys, &p.Pvpropertyid, &p.Pvuniqueid, &p.Pvvalue, &p.Pvdescription, &p.Pvbeforesave, &p.Pvaftersave, &p.Pvbeforefield, &p.Pvafterfield, &p.Pvadditional, &p.EquinoxLrn, &p.EquinoxSec)
	if err != nil {
		return nil, err
	}

	return &p, nil
}
