// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// SmartsvrBlb represents a row from 'equinox.smartsvr_blb'.
type SmartsvrBlb struct {
	BlbLrn  int64          `json:"blb_lrn"`  // blb_lrn
	BlbData []byte         `json:"blb_data"` // blb_data
	BlbText sql.NullString `json:"blb_text"` // blb_text
}

func AllSmartsvrBlb(db XODB, callback func(x SmartsvrBlb) bool) error {

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.smartsvr_blb `

	q, err := db.Query(sqlstr)

	if err != nil {
		return err
	}
	defer q.Close()

	// load results
	for q.Next() {
		sb := SmartsvrBlb{}

		// scan
		err = q.Scan(&sb.BlbLrn, &sb.BlbData, &sb.BlbText)
		if err != nil {
			return err
		}
		if !callback(sb) {
			return nil
		}
	}

	return nil
}

// SmartsvrBlbByBlbLrn retrieves a row from 'equinox.smartsvr_blb' as a SmartsvrBlb.
//
// Generated from index 'smartsvr_blb_pkey'.
func SmartsvrBlbByBlbLrn(db XODB, blbLrn int64) (*SmartsvrBlb, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.smartsvr_blb ` +
		`WHERE blb_lrn = $1`

	// run query
	XOLog(sqlstr, blbLrn)
	sb := SmartsvrBlb{}

	err = db.QueryRow(sqlstr, blbLrn).Scan(&sb.BlbLrn, &sb.BlbData, &sb.BlbText)
	if err != nil {
		return nil, err
	}

	return &sb, nil
}
