// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// TprtoregBlb represents a row from 'equinox.tprtoreg_blb'.
type TprtoregBlb struct {
	BlbLrn  int64          `json:"blb_lrn"`  // blb_lrn
	BlbData []byte         `json:"blb_data"` // blb_data
	BlbText sql.NullString `json:"blb_text"` // blb_text
}

// TprtoregBlbByBlbLrn retrieves a row from 'equinox.tprtoreg_blb' as a TprtoregBlb.
//
// Generated from index 'tprtoreg_blb_pkey'.
func TprtoregBlbByBlbLrn(db XODB, blbLrn int64) (*TprtoregBlb, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.tprtoreg_blb ` +
		`WHERE blb_lrn = $1`

	// run query
	XOLog(sqlstr, blbLrn)
	tb := TprtoregBlb{}

	err = db.QueryRow(sqlstr, blbLrn).Scan(&tb.BlbLrn, &tb.BlbData, &tb.BlbText)
	if err != nil {
		return nil, err
	}

	return &tb, nil
}
