// Package billmodel contains the types for schema 'equinox'.
package billmodel

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// VccommdtBlb represents a row from 'equinox.vccommdt_blb'.
type VccommdtBlb struct {
	BlbLrn  int64          `json:"blb_lrn"`  // blb_lrn
	BlbData []byte         `json:"blb_data"` // blb_data
	BlbText sql.NullString `json:"blb_text"` // blb_text
}

func AllVccommdtBlb(db XODB, callback func(x VccommdtBlb) bool) error {

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.vccommdt_blb `

	q, err := db.Query(sqlstr)

	if err != nil {
		return err
	}
	defer q.Close()

	// load results
	for q.Next() {
		vb := VccommdtBlb{}

		// scan
		err = q.Scan(&vb.BlbLrn, &vb.BlbData, &vb.BlbText)
		if err != nil {
			return err
		}
		if !callback(vb) {
			return nil
		}
	}

	return nil
}

// VccommdtBlbByBlbLrn retrieves a row from 'equinox.vccommdt_blb' as a VccommdtBlb.
//
// Generated from index 'vccommdt_blb_pkey'.
func VccommdtBlbByBlbLrn(db XODB, blbLrn int64) (*VccommdtBlb, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`blb_lrn, blb_data, blb_text ` +
		`FROM equinox.vccommdt_blb ` +
		`WHERE blb_lrn = $1`

	// run query
	XOLog(sqlstr, blbLrn)
	vb := VccommdtBlb{}

	err = db.QueryRow(sqlstr, blbLrn).Scan(&vb.BlbLrn, &vb.BlbData, &vb.BlbText)
	if err != nil {
		return nil, err
	}

	return &vb, nil
}
